### ISSUE TITLE
Dark mode switch shows briefly in some instances

### ISSUE THREAD

**Issue by rkokeza** [Mediteran2910/rest-countries-api#2]
Icon in the upper right corner that switches between dark and light mode is briefly shown (<500ms), when there are multiple refreshes in succession.

Button in question:
https://github.com/Mediteran2910/rest-countries-api/blob/335653ce212a7ffd52028fd9f3ae60433c607758/index.html#L15-L17

Reproduction steps:
1. Open home page
2. Click refresh 4 times

**Comment by Mediteran2910** [comment]
Thanks Rocco, I really appreciate it!
